language: ruby
rvm:
  - 2.3.3
cache: bundler
script: bundle exec middleman build --clean
deploy:
  provider: s3
  access_key_id: AKIAJ6SJ4QL2VOMCID5A
  secret_access_key:
    secure: "D5NJmQhbnCICmgnaBKlXb1m7MZd2pYRADzNaUbHj6yNzbg9hbBG+XTohlCbqBB+TK/vVS0XyFqieayIBoGQYByzo1u8V7EHFWX3ZiOXA9r1P8C3t8IbBKi7ZtCqbGcEd7f3PBzyQpIXfyTSclx4yL01MMGhwfci65ILb8w4Bdzq1NHyRJt4z2Ky5PW3pIpGpHdfxVcGC21d+6ewSg+mwb5RqvIke8Ngkglw8j79MftYlrfOB3GmNNko97K7GsvqaGisNKJPWpSdKztN8IRxXz1ocLjCLkuxbe1sVUN4/GnqCRnjzJ5EU1OlrNO11TzGTw4quFZ0rTmvkftdr9OD1bBhdS0j/HPTCIdZy3m8tyb1Z9Db4X/QZuPFwKzDduohZsVAf5iN+6xE706fBPDNu8hlXeWoRC/qpPqc73g2c40GxPigiMLtUd9rbHYxf0jpRKKBV7S3Wv9hYdZgSLIxAnfAg2vokZtoJ+KJWKVL5wczjhsJc+Jj0Cdn86jzhLFLgafdVFeMIRh9xWOvtbpbgy7PVW2dMliHdzbsb1LyFHsYAHvixp2ThPH6JxZ7xYyiWTdqd3aYN+HMziudD+BjOCY1FRxRHd55DNCq3diJPrWYAP3olTorKvBEFUKHbDbSL2sX1+8KQsb6dEnqkGji5yECKDY58HPPgWFj/HaR6J2o="
  bucket: "docs.talklifeclarity.com"
  region: "eu-west-1"
  skip_cleanup: true
  local_dir: build